name: trustcard
description: A digital ID verification app for workers and customers
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  go_router: ^14.2.7
  
  # QR Code & Camera
  qr_flutter: ^4.1.0
  # mobile_scanner: ^7.1.2  # Temporarily disabled due to iOS 26 compatibility
  camera: ^0.11.2
  
  # Image handling
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  
  # State management
  provider: ^6.1.2
  
  # HTTP & API
  http: ^1.2.2
  dio: ^5.7.0
  
  # Local storage
  shared_preferences: ^2.3.2
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  firebase_messaging: ^15.1.3
  
  # Authentication
  # google_sign_in: ^6.2.1  # Temporarily disabled due to iOS 26 compatibility
  # sign_in_with_apple: ^6.1.1  # Temporarily disabled due to iOS 26 compatibility
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  permission_handler: ^12.0.1
  
  # UI Components
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
