// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANs2tXgeiPcmXZOPaMyCK-nlf3qEHBh1s',
    appId: '1:818303002429:web:1a7tpmhf3ec1rjraijbgq6aiea3p31ho',
    messagingSenderId: '818303002429',
    projectId: 'trustcard-aee4a',
    authDomain: 'trustcard-aee4a.firebaseapp.com',
    storageBucket: 'trustcard-aee4a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANs2tXgeiPcmXZOPaMyCK-nlf3qEHBh1s',
    appId: '1:818303002429:android:2b39d9b9ea830fe5b88754',
    messagingSenderId: '818303002429',
    projectId: 'trustcard-aee4a',
    storageBucket: 'trustcard-aee4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkHqD483HBZQIxUfFODnmQqwGDzwR2j1I',
    appId: '1:818303002429:ios:df5ce41870afd64cb88754',
    messagingSenderId: '818303002429',
    projectId: 'trustcard-aee4a',
    storageBucket: 'trustcard-aee4a.firebasestorage.app',
    iosBundleId: 'com.accexasia.TrustCard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkHqD483HBZQIxUfFODnmQqwGDzwR2j1I',
    appId: '1:818303002429:ios:df5ce41870afd64cb88754',
    messagingSenderId: '818303002429',
    projectId: 'trustcard-aee4a',
    storageBucket: 'trustcard-aee4a.firebasestorage.app',
    iosBundleId: 'com.accexasia.TrustCard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANs2tXgeiPcmXZOPaMyCK-nlf3qEHBh1s',
    appId: '1:818303002429:web:1a7tpmhf3ec1rjraijbgq6aiea3p31ho',
    messagingSenderId: '818303002429',
    projectId: 'trustcard-aee4a',
    authDomain: 'trustcard-aee4a.firebaseapp.com',
    storageBucket: 'trustcard-aee4a.firebasestorage.app',
  );
}
